title: 洪清档案 The Dream of Hong
theme: minima
url: "https://huangzhuowu.github.io"
baseurl: "/The-Dream-of-Hong"   


collections:
  history:
    output: true
    permalink: /history/:name/
  entertainment:
    output: true
    permalink: /entertainment/:name/
  metaphysics:
    output: true
    permalink: /metaphysics/:name/

defaults:
  - scope:
      path: ""          # 留空即可
      type: history     # 作用到 history 集合
    values:
      layout: item
      area: history

  - scope:
      path: ""
      type: entertainment
    values:
      layout: item
      area: entertainment

  - scope:
      path: ""
      type: metaphysics
    values:
      layout: item
      area: metaphysics


# 以后要做中英双语，可在 front-matter 增加 lang/en_title 等字段，或切换到 i18n 框架
